# Generated by Django 6.0 on 2026-01-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
